[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.apache.kafka#kafka_2.12;0.10.0.1: not found
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveEngine.mergeErrors(CachedResolutionResolveEngine.scala:495)
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveEngine.mergeErrors$(CachedResolutionResolveEngine.scala:483)
[error] 	at sbt.internal.librarymanagement.IvySbt$ParallelCachedResolutionResolveEngine.mergeErrors(Ivy.scala:138)
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveEngine.mergeResults(CachedResolutionResolveEngine.scala:480)
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveEngine.mergeResults$(CachedResolutionResolveEngine.scala:471)
[error] 	at sbt.internal.librarymanagement.IvySbt$ParallelCachedResolutionResolveEngine.mergeResults(Ivy.scala:138)
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveEngine.$anonfun$customResolve$1(CachedResolutionResolveEngine.scala:461)
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveEngine$$Lambda$3463/1174542227.apply(Unknown Source)
[error] 	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveCache.getOrElseUpdateProjectReport(CachedResolutionResolveEngine.scala:310)
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveEngine.customResolve(CachedResolutionResolveEngine.scala:357)
[error] 	at sbt.internal.librarymanagement.ivyint.CachedResolutionResolveEngine.customResolve$(CachedResolutionResolveEngine.scala:346)
[error] 	at sbt.internal.librarymanagement.IvySbt$ParallelCachedResolutionResolveEngine.customResolve(Ivy.scala:138)
[error] 	at sbt.internal.librarymanagement.IvyActions$.cachedResolveAndRetrieve(IvyActions.scala:377)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:207)
[error] 	at sbt.internal.librarymanagement.IvyActions$$$Lambda$1825/720640824.apply(Unknown Source)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module$$Lambda$1826/585745913.apply(Unknown Source)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt$$Lambda$1827/690070992.apply(Unknown Source)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$1797/859903114.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.util.Tracked$$$Lambda$1751/1336974496.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$1799/314241128.apply(Unknown Source)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$1793/1305296866.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.util.Tracked$$$Lambda$1700/664723414.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2561)
[error] 	at sbt.Classpaths$$$Lambda$886/2026706491.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at scala.Function1$$Lambda$602/538292941.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$1618/943472307.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.Execute$$Lambda$1639/725921946.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.Execute$$Lambda$1625/160549854.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$1632/233315297.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: unresolved dependency: org.apache.kafka#kafka_2.12;0.10.0.1: not found
